### ISSUE TITLE
Not currently working

### ISSUE THREAD

**Issue by daltabas** [dodoma700/PluralVideos#1]
I made the process to decrypt and after the process complete I can reproduce the videos. Are your planning on lunching a new version?
DecryptVideos --out <route> --db <route> --trans

**Comment by SamotCZE** [comment]
Yeah, it look like it decoded the video, the output seems ok, but video cannot be played unfortunately. Would be great if this can be solved.

**Comment by rld223** [comment]
Yeah it finds and decrypts the videos, but upon playing the file theres no video or audio

**Comment by dodoma700** [comment]
> I made the process to decrypt and after the process complete I can reproduce the videos. Are your planning on lunching a new version?
> DecryptVideos --out --db --trans

is the current version not working?

**Comment by dodoma700** [comment]
> Yeah it finds and decrypts the videos, but upon playing the file theres no video or audio

I cannot reproduce the error try Decrypt --out path

**Comment by daltabas** [comment]
> 
> 
> > Yeah it finds and decrypts the videos, but upon playing the file theres no video or audio
> 
> I cannot reproduce the error try Decrypt --out path

After triyng only Decrypt --out I get the same message
![imagen](https://user-images.githubusercontent.com/12768674/97918976-ffa58d80-1d24-11eb-8546-8483e66e540b.png)

**Comment by dodoma700** [comment]
> > > Yeah it finds and decrypts the videos, but upon playing the file theres no video or audio
> > 
> > 
> > I cannot reproduce the error try Decrypt --out path
> 
> After triyng only Decrypt --out I get the same message
> ![imagen](https://user-images.githubusercontent.com/12768674/97918976-ffa58d80-1d24-11eb-8546-8483e66e540b.png)

Have you tried to play in a different Video player like VLC?

**Comment by daltabas** [comment]
Yes I have VLC and KML Player same result

**Comment by Gribe** [comment]
Exactly same problem, it says it decrypts and outputs but VLC can't play it.
