### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by mikhaelnwankwo** [dodoma700/PluralVideos#3]
Hi, don't know how to run this app.
can you help?

**Comment by mikhaelnwankwo** [comment]
Took a few trials but finally got it working :)
<img width="541" alt="Screenshot 2020-11-15 at 14 43 09" src="https://user-images.githubusercontent.com/26689508/99186542-329e4700-2751-11eb-87c9-1af000dcd81b.png">

**Comment by MohamedAlashry** [comment]
hi dude:
please could tell me how to run it i downloaded the .exe and trird to run it with no use at all.
and cmd doesnot recognize the command.
can yo explain it to me please?

**Comment by jessiekerkhove** [comment]
> hi dude:
> please could tell me how to run it i downloaded the .exe and trird to run it with no use at all.
> and cmd doesnot recognize the command.
> can yo explain it to me please?

I have the same problem. And I'm hoping someone can help.

**Comment by reneduesmann** [comment]
Guys really? @MohamedAlashry, @jessiekerkhove 
U download the latest version and navigate with cmd or powershell to the directory of the executable.
Login to your account like:
![image](https://user-images.githubusercontent.com/73254221/101281934-67427300-37d2-11eb-9e07-73c24ea0992a.png)
After that, you download a course.
![image](https://user-images.githubusercontent.com/73254221/101282006-c2746580-37d2-11eb-8f8b-d03772c7847e.png)

**Comment by jessiekerkhove** [comment]
Is it a shame to ask how to do it? Didn't everyone start from scratch one day? :/

**Comment by reneduesmann** [comment]
@jessiekerkhove what do you mean with 'how to do it'? I explained that.
All other has nothing to do with the downloader.

**Comment by jessiekerkhove** [comment]
> @jessiekerkhove what do you mean with 'how to do it'? I explained that.
> All other has nothing to do with the downloader.

Thanks for showing how to do it it. I mean, you wrote "Guys, really"... I imagine a rolling eyes smiley next to it. So I interpret the message as it's stupid to ask how to make it work. (Sorry, I'm not native English speaker, I hope my post makes sense". )

**Comment by reneduesmann** [comment]
@jessiekerkhove Im not a english native speaker too.
But @dodoma700 explained everything in the readme file. And i´m wondered, why two people does not understand, how the program works.

**Comment by jessiekerkhove** [comment]
> @jessiekerkhove Im not a english native speaker too.
> But @dodoma700 explained everything in the readme file. And i´m wondered, why two people does not understand, how the program works.

Sorry, I didn't see it in the read me file. I'm a Powershell noob so it wasn't obvious for me how to start using the code.

**Comment by mikhaelnwankwo** [comment]
Basically the steps I took to run it for that version was:
1) install dotnet core 3.1
2) download or clone the project to your computer 
3) navigate to Sec then to pluralvideos.downloads folder in terminal or cmd
4) execute the command " dotnet run auth --login" to authenticate 
5) this will generate a six digit code, navigate to Pluralsight.com/auth while logged in already on your browser to authorize your computer by entering the generated code 
6) if done right, terminal or cmd will show the success message 
7) to download a course execute " dotnet run download --out <put-the-location-on-your-computer-here> --course <put-the-course-name-here>
8) the readme file also explained how to download a single module or full path 
Good luck!
