### ISSUE TITLE
Risk of getting banned?

### ISSUE THREAD

**Issue by KhaledAlramam** [dodoma700/PluralVideos#4]
I used youtube-dl last month and they detected it and banned me .
Is this tool save? I don't wanna risk another ban

**Comment by reneduesmann** [comment]
An Account Subscription costs 30€/$. Test it.

**Comment by KhaledAlramam** [comment]
> 
> 
> An Account Subscription costs 30€/$. Test it.

Thanks i tried the decrypt and it worked
