### ISSUE TITLE
Downloader does not load all files

### ISSUE THREAD

**Issue by reneduesmann** [dodoma700/PluralVideos#5]
You fixed my last issue, that the downloader can not retrieve all courses.
But for the same course, the downloader does not load 2 files, see the screenshot.
![image](https://user-images.githubusercontent.com/73254221/99361242-1665eb80-28b2-11eb-9ebb-0a1f545d8693.png)

It is the course 'SharePoint Server 2013 Core Solutions (70-331) Part 1'

Thank you.

Another question, can i contact you on some way? I have some questions from developer to developer.

**Comment by dodoma700** [comment]
> You fixed my last issue, that the downloader can not retrieve all courses.
> But for the same course, the downloader does not load 2 files, see the screenshot.
> ![image](https://user-images.githubusercontent.com/73254221/99361242-1665eb80-28b2-11eb-9ebb-0a1f545d8693.png)
> 
> It is the course 'SharePoint Server 2013 Core Solutions (70-331) Part 1'
> 
> Thank you.
> 
> Another question, can i contact you on some way? I have some questions from developer to developer.

I have temporary solution of reducing the number of threads. the default is 10. Use 4 by the command 
download --out <location> --course <course name> --threads 4

**Comment by dodoma700** [comment]
> You fixed my last issue, that the downloader can not retrieve all courses.
> But for the same course, the downloader does not load 2 files, see the screenshot.
> ![image](https://user-images.githubusercontent.com/73254221/99361242-1665eb80-28b2-11eb-9ebb-0a1f545d8693.png)
> 
> It is the course 'SharePoint Server 2013 Core Solutions (70-331) Part 1'
> 
> Thank you.
> 
> Another question, can i contact you on some way? I have some questions from developer to developer.

Alternative use the --list flag to the clip code and then use --clip <clip_code> to download that partcular video

**Comment by reneduesmann** [comment]
I will test it.

And my last question, Can we get in touch somehow?
